apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "nodes", "namespaces","pods/log"]
  verbs: ["get", "list",]

